// SPDX-FileCopyrightText: Copyright (c) Stanford University, The Regents of the
// University of California, and others. SPDX-License-Identifier: BSD-3-Clause

/// @file

#include "ActiveStressRegazzoni.h"
#include "active_stress_test_helpers.h"
#include "gtest/gtest.h"

/**
 * @test Run a standalone ActiveStressRegazzoni twitch for 600 updates with
 * @f$\Delta t=1\,\mathrm{ms}@f$ and the prescribed calcium and fiber-stretch
 * trajectories.
 *
 * The trusted reference was produced with the authors'
 * [cardiac-activation](https://github.com/FrancescoRegazzoni/cardiac-activation)
 * C++ implementation at commit
 * @c 26f05df28891df7b3c69f16bb136cdced6b63c4d; it was not generated by
 * svMultiPhysics. See
 * @c reference_generators/active_stress/regazzoni/README.md for source
 * provenance and reproduction details, and @ref ActiveStressRegazzoni for the
 * model equations, numerical update, and state ordering.
 */
TEST(ActiveStressTrajectory, Regazzoni) {
  ActiveStressRegazzoni::Parameters params;

  ActiveStressTrajectoryConfiguration configuration;
  configuration.final_time = 600.0;
  configuration.time_step = 1.0;
  configuration.reference_csv_filename =
      "active_stress_regazzoni_twitch.csv";

  ActiveStressTrajectoryTest<ActiveStressRegazzoni> trajectory(
      params, configuration);
  trajectory.run();
}
