# SPDX-License-Identifier: CC-BY-3.0

# Adapted from Python generated by libCellML 0.6.3 from the active_tension
# component of the Physiome Nash--Panfilov 2004 CellML model.
# CellML model author: Martyn Nash; document metadata also names David Nickerson.
# License: https://creativecommons.org/licenses/by/3.0/
# Changes to generated Python: voltage activation, the rate law, and target
# tension were adapted to the svMP calcium-driven formulation; unused generated
# helpers were removed.
# See README.md for the exact source, revision, hashes, and generation steps.

"""Physiome-derived Nash--Panfilov active-tension model core."""

from enum import Enum
from math import *


__version__ = "0.4.0"
LIBCELLML_VERSION = "0.6.3"

STATE_COUNT = 1
VARIABLE_COUNT = 8


class VariableType(Enum):
    VARIABLE_OF_INTEGRATION = 0
    STATE = 1
    CONSTANT = 2
    COMPUTED_CONSTANT = 3
    ALGEBRAIC = 4
    EXTERNAL = 5


VOI_INFO = {
    "name": "t",
    "units": "ms",
    "component": "active_tension",
    "type": VariableType.VARIABLE_OF_INTEGRATION,
}

STATE_INFO = [
    {
        "name": "Ta",
        "units": "kPa",
        "component": "active_tension",
        "type": VariableType.STATE,
    }
]

VARIABLE_INFO = [
    {
        "name": "calcium",
        "units": "mM",
        "component": "active_tension",
        "type": VariableType.EXTERNAL,
    },
    {
        "name": "eta_T",
        "units": "kPa_per_mM",
        "component": "active_tension",
        "type": VariableType.CONSTANT,
    },
    {
        "name": "epsilon",
        "units": "per_ms",
        "component": "active_tension",
        "type": VariableType.ALGEBRAIC,
    },
    {
        "name": "epsilon_0",
        "units": "per_ms",
        "component": "active_tension",
        "type": VariableType.CONSTANT,
    },
    {
        "name": "epsilon_i",
        "units": "per_ms",
        "component": "active_tension",
        "type": VariableType.CONSTANT,
    },
    {
        "name": "xi_T",
        "units": "per_mM",
        "component": "active_tension",
        "type": VariableType.CONSTANT,
    },
    {
        "name": "calcium_rest",
        "units": "mM",
        "component": "active_tension",
        "type": VariableType.CONSTANT,
    },
    {
        "name": "calcium_crit",
        "units": "mM",
        "component": "active_tension",
        "type": VariableType.CONSTANT,
    },
]


def create_states_array():
    return [nan] * STATE_COUNT


def create_variables_array():
    return [nan] * VARIABLE_COUNT


def initialise_variables(voi, states, rates, variables, external_variable):
    variables[1] = 1.0e2
    variables[3] = 0.1
    variables[4] = 1.0
    variables[5] = 4.0e3
    variables[6] = 1.25e-4
    variables[7] = 8.0e-4
    variables[0] = external_variable(voi, states, rates, variables, 0)


def compute_rates(voi, states, rates, variables, external_variable):
    variables[0] = external_variable(voi, states, rates, variables, 0)
    variables[2] = variables[3] + (variables[4] - variables[3]) * exp(
        -exp(-variables[5] * (variables[0] - variables[7]))
    )
    rates[0] = variables[2] * (
        variables[1] * (variables[0] - variables[6]) - states[0]
    )
