#!/usr/bin/env python3
"""Qualify P1 level-set advection of moving contact points on impermeable walls.

This is a production ApplicationDriver/TimeLoop transport-isolation gate.  A
vertical P1 interface is advected by the prescribed divergence-free velocity
generated by ``psi=A*x*(1-x/L)*y*(H-y)``.  All four walls are closed and have
identically zero normal velocity.  The bottom and top contact points move in
opposite tangential directions, while wall vertices ahead of the interface
remain exactly dry.  Backward RK4 characteristics supply the reference field;
no scalar inflow condition or open-boundary shortcut is used.

The gate does not exercise the Navier--Stokes momentum or contact-line force
operators and must not be reported as a dynamic-wetting benchmark.

The profile records strict one-ring excursions but permits an explicitly
capped qualification-scale numerical slack for the non-DMP spatial operator.
That slack does not alter the independent sign, false-wet, accuracy, contact,
or refinement gates and is not an invariant-domain certification.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

import numpy as np
import pyvista as pv


HERE = Path(__file__).resolve().parent
GENERATOR = (
    HERE / "unfitted_level_set/mms_traveling_interface_2d/generate_case.py"
)
ACCEPTED_RE = re.compile(
    r"TimeLoop: step_accepted step=(?P<step>[0-9]+) "
    r"time=(?P<time>[-+0-9.eE]+) dt=(?P<dt>[-+0-9.eE]+)"
)
REJECTED_RE = re.compile(r"TimeLoop: step_rejected step=(?P<step>[0-9]+)")
RESULT_RE = re.compile(r"result_(?P<step>[0-9]+)\.vtu$")

# Fixed before execution.  They scale only with the declared mesh size.
MAX_PHI_RMS_OVER_H = 5.0e-2
MAX_PHI_MAX_OVER_H = 1.5e-1
MAX_CONTACT_ERROR_OVER_H = 2.5e-1
DRY_SIGN_MARGIN_OVER_H = 2.0e-2
MIN_PHI_RMS_REFINEMENT_RATE = 0.5
REFINEMENT_EXACTNESS_FLOOR = 1.0e-12
TIME_TOLERANCE = 1.0e-12

# Even at a converged nonlinear residual, this non-DMP spatial discretization
# can produce deterministic sub-microscale excursions beyond the previous
# one-ring coefficient range.  Permit an unprojected excursion of at most one
# millionth of the level-set distance scale.  This is a qualification-scale
# numerical representability allowance, not invariant-domain certification or
# a physical sign/accuracy tolerance: sign classification remains at 1e-12,
# the accepted history is audited independently for sign flips, and the slack
# must remain at least two orders of magnitude below the dry-wall sign margin.
MAX_BOUND_REPRESENTABILITY_SLACK_OVER_LENGTH = 1.0e-6
BOUND_SIGN_TOLERANCE = 1.0e-12
MAX_SLACK_FRACTION_OF_DRY_SIGN_MARGIN = 1.0e-2

LENGTH = 1.0
DEFAULT_BOUND_REPRESENTABILITY_SLACK = (
    MAX_BOUND_REPRESENTABILITY_SLACK_OVER_LENGTH * LENGTH
)
FRONT_INITIAL_X = 0.30
TANK_HEIGHT = 0.30
FINAL_TIME = 0.10
GENERATOR_DEPTH = 0.15
GENERATOR_AMPLITUDE = 0.02
STREAMFUNCTION_AMPLITUDE = 4.0
CHARACTERISTIC_SUBSTEPS = 512
FIXED_TIME_STEPS = 512


def xml_real(value: float) -> str:
    """Return a stable, round-trippable XML representation of a real."""
    return f"{value:.16e}"


def validate_bound_representability_slack(
        slack: float, resolutions: list[int]) -> None:
    """Keep numerical bound slack separated from physical wall-sign gates."""
    maximum = MAX_BOUND_REPRESENTABILITY_SLACK_OVER_LENGTH * LENGTH
    if not math.isfinite(slack) or slack < 0.0 or slack > maximum:
        raise ValueError(
            "bound representability slack must be finite and in "
            f"[0, {maximum:.6g}]")
    finest_h = LENGTH / max(resolutions)
    dry_sign_margin = DRY_SIGN_MARGIN_OVER_H * finest_h
    if slack > MAX_SLACK_FRACTION_OF_DRY_SIGN_MARGIN * dry_sign_margin:
        raise ValueError(
            "bound representability slack must remain at least two orders of "
            "magnitude below the finest-grid dry sign margin; reduce "
            "--bound-representability-slack")


def accepted_clock(log: str) -> tuple[dict[int, dict[str, float]], list[str]]:
    clock: dict[int, dict[str, float]] = {}
    errors: list[str] = []
    for match in ACCEPTED_RE.finditer(log):
        step = int(match.group("step"))
        record = {
            "time": float(match.group("time")),
            "dt": float(match.group("dt")),
        }
        previous = clock.get(step)
        if previous is not None and previous != record:
            errors.append(f"conflicting accepted clock for step {step}")
        clock[step] = record
    ordered = sorted(clock.items())
    for (previous_step, previous), (step, record) in zip(
            ordered[:-1], ordered[1:]):
        if step <= previous_step or record["time"] <= previous["time"]:
            errors.append("accepted-step clock is not strictly increasing")
        if not math.isfinite(record["dt"]) or record["dt"] <= 0.0:
            errors.append(f"accepted step {step} has invalid dt")
    return clock, errors


def point_values_in_initial_order(initial: pv.DataSet,
                                  output: pv.DataSet,
                                  name: str) -> np.ndarray:
    initial_ids = np.asarray(initial.point_data["GlobalNodeID"], dtype=np.int64)
    output_ids = np.asarray(output.point_data["GlobalNodeID"], dtype=np.int64)
    by_id = {int(gid): index for index, gid in enumerate(output_ids)}
    missing = [int(gid) for gid in initial_ids if int(gid) not in by_id]
    if missing:
        raise ValueError(f"output omits {len(missing)} initial node ids")
    indices = np.asarray([by_id[int(gid)] for gid in initial_ids], dtype=np.int64)
    return np.asarray(output.point_data[name], dtype=float).reshape(-1)[indices]


def one_ring_bound_metrics(mesh: pv.DataSet,
                           previous_phi: np.ndarray,
                           candidate_phi: np.ndarray,
                           representability_slack: float,
                           sign_tolerance: float) -> dict[str, Any]:
    """Independently audit strict and slack-relative one-ring excursions."""
    previous = np.asarray(previous_phi, dtype=float).reshape(-1)
    candidate = np.asarray(candidate_phi, dtype=float).reshape(-1)
    if previous.shape != candidate.shape or previous.size != mesh.n_points:
        raise ValueError("one-ring audit received incompatible nodal fields")
    lower = np.full(previous.shape, np.inf, dtype=float)
    upper = np.full(previous.shape, -np.inf, dtype=float)
    for cell_index in range(mesh.n_cells):
        point_ids = np.asarray(
            mesh.get_cell(cell_index).point_ids, dtype=np.int64)
        if point_ids.size == 0:
            raise ValueError("one-ring audit found an empty cell")
        cell_values = previous[point_ids]
        cell_minimum = float(np.min(cell_values))
        cell_maximum = float(np.max(cell_values))
        lower[point_ids] = np.minimum(lower[point_ids], cell_minimum)
        upper[point_ids] = np.maximum(upper[point_ids], cell_maximum)
    if not (np.all(np.isfinite(lower)) and np.all(np.isfinite(upper))):
        raise ValueError("one-ring audit found an unvisited mesh point")

    strict_violation = np.maximum.reduce((
        np.zeros(candidate.shape, dtype=float),
        lower - candidate,
        candidate - upper,
    ))
    scale = np.maximum.reduce((
        np.ones(candidate.shape, dtype=float),
        np.abs(lower),
        np.abs(upper),
    ))
    slack_exceeded = strict_violation > representability_slack * scale
    positive_flips = (lower > sign_tolerance) & (
        candidate < -sign_tolerance)
    negative_flips = (upper < -sign_tolerance) & (
        candidate > sign_tolerance)
    return {
        "strict_one_ring_bound_violation_dofs": int(
            np.count_nonzero(strict_violation > 0.0)),
        "maximum_strict_one_ring_bound_violation": float(
            np.max(strict_violation)),
        "representability_slack_exceeded_dofs": int(
            np.count_nonzero(slack_exceeded)),
        "positive_patch_sign_flips": int(np.count_nonzero(positive_flips)),
        "negative_patch_sign_flips": int(np.count_nonzero(negative_flips)),
    }


def streamfunction_velocity(points: np.ndarray) -> np.ndarray:
    coordinates = np.asarray(points, dtype=float)
    x = coordinates[:, 0]
    y = coordinates[:, 1]
    velocity = np.zeros((coordinates.shape[0], 3), dtype=float)
    velocity[:, 0] = (
        STREAMFUNCTION_AMPLITUDE * x * (1.0 - x / LENGTH) *
        (TANK_HEIGHT - 2.0 * y)
    )
    velocity[:, 1] = (
        -STREAMFUNCTION_AMPLITUDE * (1.0 - 2.0 * x / LENGTH) *
        y * (TANK_HEIGHT - y)
    )
    return velocity


def characteristic_map(points: np.ndarray, time_s: float) -> np.ndarray:
    coordinates = np.asarray(points, dtype=float).copy()
    if time_s == 0.0:
        return coordinates
    substeps = max(
        1,
        int(math.ceil(
            abs(time_s) / FINAL_TIME * CHARACTERISTIC_SUBSTEPS)),
    )
    step = time_s / substeps
    for _ in range(substeps):
        k1 = streamfunction_velocity(coordinates)
        k2 = streamfunction_velocity(coordinates + 0.5 * step * k1)
        k3 = streamfunction_velocity(coordinates + 0.5 * step * k2)
        k4 = streamfunction_velocity(coordinates + step * k3)
        coordinates += step * (k1 + 2.0 * k2 + 2.0 * k3 + k4) / 6.0
    return coordinates


def exact_phi(points: np.ndarray, time_s: float) -> np.ndarray:
    departure_points = characteristic_map(points, -time_s)
    return departure_points[:, 0] - FRONT_INITIAL_X


def exact_phi_history(points: np.ndarray,
                      times: list[float]) -> list[np.ndarray]:
    """Evaluate all backward-characteristic references in one RK4 march."""
    coordinates = np.asarray(points, dtype=float).copy()
    history: list[np.ndarray] = []
    previous_time = 0.0
    for time_s in times:
        if time_s < previous_time - TIME_TOLERANCE:
            raise ValueError("characteristic reference times must be ordered")
        interval = max(0.0, time_s - previous_time)
        substeps = (
            max(1, int(math.ceil(
                interval / FINAL_TIME * CHARACTERISTIC_SUBSTEPS)))
            if interval > 0.0 else 0
        )
        step = -interval / substeps if substeps else 0.0
        for _ in range(substeps):
            k1 = streamfunction_velocity(coordinates)
            k2 = streamfunction_velocity(coordinates + 0.5 * step * k1)
            k3 = streamfunction_velocity(coordinates + 0.5 * step * k2)
            k4 = streamfunction_velocity(coordinates + step * k3)
            coordinates += step * (
                k1 + 2.0 * k2 + 2.0 * k3 + k4) / 6.0
        history.append(coordinates[:, 0].copy() - FRONT_INITIAL_X)
        previous_time = time_s
    return history


def horizontal_wall_contact_points(points: np.ndarray,
                                   phi: np.ndarray,
                                   wall_y: float) -> list[float]:
    indices = np.flatnonzero(np.isclose(points[:, 1], wall_y, atol=1.0e-12))
    indices = indices[np.argsort(points[indices, 0])]
    contacts: list[float] = []
    for left, right in zip(indices[:-1], indices[1:]):
        f0 = float(phi[left])
        f1 = float(phi[right])
        x0 = float(points[left, 0])
        x1 = float(points[right, 0])
        if f0 == 0.0:
            contacts.append(x0)
        if f0 * f1 < 0.0:
            contacts.append(x0 + (x1 - x0) * f0 / (f0 - f1))
    if indices.size and float(phi[indices[-1]]) == 0.0:
        contacts.append(float(points[indices[-1], 0]))
    deduplicated: list[float] = []
    for value in sorted(contacts):
        if not deduplicated or abs(value - deduplicated[-1]) > 1.0e-12:
            deduplicated.append(value)
    return deduplicated


def exact_horizontal_wall_contacts(time_s: float,
                                   wall_y: float) -> list[float]:
    initial = np.asarray([[FRONT_INITIAL_X, wall_y, 0.0]], dtype=float)
    return [float(characteristic_map(initial, time_s)[0, 0])]


def contact_error(measured: list[float], expected: list[float]) -> float | None:
    if len(measured) != len(expected):
        return None
    return max(
        abs(a - b)
        for a, b in zip(sorted(measured), sorted(expected))
    )


def state_metrics(initial: pv.DataSet,
                  output: pv.DataSet,
                  step: int,
                  time_s: float,
                  dt: float,
                  h: float,
                  expected_phi: np.ndarray | None = None) -> dict[str, Any]:
    points = np.asarray(initial.points, dtype=float)
    phi = point_values_in_initial_order(initial, output, "phi")
    expected = (
        exact_phi(points, time_s)
        if expected_phi is None else np.asarray(expected_phi, dtype=float)
    )
    if expected.shape != phi.shape:
        raise ValueError("exact level-set reference has the wrong shape")
    error = phi - expected
    y_min = float(np.min(points[:, 1]))
    y_max = float(np.max(points[:, 1]))
    x_min = float(np.min(points[:, 0]))
    x_max = float(np.max(points[:, 0]))
    impermeable = (
        np.isclose(points[:, 1], y_min, atol=1.0e-12) |
        np.isclose(points[:, 1], y_max, atol=1.0e-12) |
        np.isclose(points[:, 0], x_min, atol=1.0e-12) |
        np.isclose(points[:, 0], x_max, atol=1.0e-12)
    )
    dry_margin = DRY_SIGN_MARGIN_OVER_H * h
    exact_dry = impermeable & (expected >= dry_margin)
    false_liquid = exact_dry & (phi <= 0.0)
    measured_bottom = horizontal_wall_contact_points(points, phi, y_min)
    expected_bottom = exact_horizontal_wall_contacts(time_s, y_min)
    bottom_error = contact_error(measured_bottom, expected_bottom)
    measured_top = horizontal_wall_contact_points(points, phi, y_max)
    expected_top = exact_horizontal_wall_contacts(time_s, y_max)
    top_error = contact_error(measured_top, expected_top)
    return {
        "step": step,
        "time": time_s,
        "dt": dt,
        "phi_rms_error": float(math.sqrt(float(np.mean(error * error)))),
        "phi_max_abs_error": float(np.max(np.abs(error))),
        "impermeable_wall_exact_dry_nodes": int(np.count_nonzero(exact_dry)),
        "impermeable_wall_false_liquid_nodes": int(np.count_nonzero(false_liquid)),
        "minimum_computed_phi_on_exact_dry_wall": (
            float(np.min(phi[exact_dry])) if np.any(exact_dry) else None
        ),
        "measured_bottom_contact_points": measured_bottom,
        "expected_bottom_contact_points": expected_bottom,
        "bottom_contact_count": len(measured_bottom),
        "bottom_contact_max_position_error": bottom_error,
        "measured_top_contact_points": measured_top,
        "expected_top_contact_points": expected_top,
        "top_contact_count": len(measured_top),
        "top_contact_max_position_error": top_error,
    }


def generate_case(
        case_dir: Path,
        resolution: int,
        bound_representability_slack: float = (
            DEFAULT_BOUND_REPRESENTABILITY_SLACK),
) -> subprocess.CompletedProcess[str]:
    validate_bound_representability_slack(
        bound_representability_slack, [resolution])
    case_dir.mkdir(parents=True, exist_ok=False)
    shutil.copy2(GENERATOR, case_dir / "generate_case.py")
    steps = FIXED_TIME_STEPS
    completed = subprocess.run(
        [
            sys.executable,
            "generate_case.py",
            "--nx", str(resolution),
            "--ny", str(resolution),
            "--element-order", "1",
            "--length", str(LENGTH),
            "--depth", str(GENERATOR_DEPTH),
            "--amplitude", str(GENERATOR_AMPLITUDE),
            "--tank-height", str(TANK_HEIGHT),
            "--u0", "0",
            "--omega", "0",
            "--time-steps", str(steps),
            "--final-time", str(FINAL_TIME),
            "--output-cadence", "1",
            "--level-set-velocity-source", "prescribed_data",
            "--level-set-only",
            "--enable-p1-transport-safety",
            "--disable-reinitialization",
        ],
        cwd=case_dir,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if completed.returncode == 0:
        mesh_path = case_dir / "mesh/background/mesh-complete.mesh.vtu"
        mesh = pv.read(mesh_path)
        points = np.asarray(mesh.points, dtype=float)
        mesh.point_data["phi"] = exact_phi(points, 0.0)
        mesh.point_data["LevelSetAdvectionVelocity"] = (
            streamfunction_velocity(points)
        )
        mesh.save(mesh_path, binary=False)

        solver_xml = case_dir / "solver.xml"
        tree = ET.parse(solver_xml)
        level_set = next(
            equation for equation in tree.getroot().findall("Add_equation")
            if equation.attrib.get("type") == "level_set"
        )
        for name in (
                "Use_wet_extension_advection_velocity",
                "Advection_velocity_from_field"):
            node = level_set.find(name)
            if node is not None:
                level_set.remove(node)
        numerical_contract = {
            "Bound_preserving_bound_tolerance":
                bound_representability_slack,
            "Bound_preserving_sign_tolerance": BOUND_SIGN_TOLERANCE,
        }
        for name, value in numerical_contract.items():
            node = level_set.find(name)
            if node is None:
                node = ET.SubElement(level_set, name)
            node.text = xml_real(value)
        for solver in tree.getroot().iter("LS"):
            solver.set("type", "GMRES")
            linear_algebra = solver.find("Linear_algebra")
            if linear_algebra is None:
                linear_algebra = ET.SubElement(solver, "Linear_algebra")
            linear_algebra.set("type", "fsils")
            preconditioner = linear_algebra.find("Preconditioner")
            if preconditioner is None:
                preconditioner = ET.SubElement(linear_algebra, "Preconditioner")
            preconditioner.text = "fsils"
        ET.indent(tree, space="  ")
        tree.write(solver_xml, encoding="utf-8", xml_declaration=True)
    return completed


def deck_contract(
        case_dir: Path,
        bound_representability_slack: float = (
            DEFAULT_BOUND_REPRESENTABILITY_SLACK),
) -> dict[str, Any]:
    root = ET.parse(case_dir / "solver.xml").getroot()
    general = root.find("GeneralSimulationParameters")
    if general is None:
        raise ValueError("solver deck has no GeneralSimulationParameters")
    level_set = next(
        equation for equation in root.findall("Add_equation")
        if equation.attrib.get("type") == "level_set"
    )
    bcs = {
        bc.attrib.get("name"): (bc.findtext("Type") or "").strip()
        for bc in level_set.findall("Add_BC")
    }
    expected = {
        "Element_order": "1",
        "Velocity_source": "prescribed_data",
        "Velocity_field_name": "LevelSetAdvectionVelocity",
        "Auto_register_velocity_field": "true",
        "Enable_SUPG": "true",
        "SUPG_transient_scale": "2.0",
        "Enable_discontinuity_capturing": "true",
        "Enable_bound_preserving_limiter": "true",
        "Bound_preserving_bound_tolerance":
            xml_real(bound_representability_slack),
        "Bound_preserving_sign_tolerance": xml_real(BOUND_SIGN_TOLERANCE),
        "Bound_preserving_enforce_courant_limit": "true",
        "Bound_preserving_enforce_impermeable_boundaries": "true",
        "Bound_preserving_impermeable_normal_velocity_tolerance": "1.0e-12",
        "Enable_reinitialization": "false",
        "Enable_volume_correction": "false",
    }
    actual = {name: (level_set.findtext(name) or "").strip()
              for name in expected}
    errors = [
        f"{name}={actual[name]!r}, expected {value!r}"
        for name, value in expected.items() if actual[name] != value
    ]
    if bcs:
        errors.append(f"unexpected level-set boundary contract: {bcs}")
    time_steps = int((general.findtext("Number_of_time_steps") or "0").strip())
    time_step_size = float(
        (general.findtext("Time_step_size") or "nan").strip())
    expected_dt = FINAL_TIME / FIXED_TIME_STEPS
    if time_steps != FIXED_TIME_STEPS:
        errors.append(
            f"Number_of_time_steps={time_steps}, expected {FIXED_TIME_STEPS}")
    if (not math.isfinite(time_step_size) or
            abs(time_step_size - expected_dt) > TIME_TOLERANCE):
        errors.append(
            f"Time_step_size={time_step_size!r}, expected {expected_dt!r}")
    if level_set.find("Use_wet_extension_advection_velocity") is not None:
        errors.append("qualification must use the prescribed mesh velocity directly")
    if level_set.find("Advection_velocity_from_field") is not None:
        errors.append("qualification must not invoke wet-side velocity extension")

    mesh = pv.read(case_dir / "mesh/background/mesh-complete.mesh.vtu")
    points = np.asarray(mesh.points, dtype=float)
    velocity = np.asarray(
        mesh.point_data["LevelSetAdvectionVelocity"], dtype=float)
    on_left_or_right = (
        np.isclose(points[:, 0], 0.0, atol=1.0e-12) |
        np.isclose(points[:, 0], LENGTH, atol=1.0e-12)
    )
    on_bottom_or_top = (
        np.isclose(points[:, 1], 0.0, atol=1.0e-12) |
        np.isclose(points[:, 1], TANK_HEIGHT, atol=1.0e-12)
    )
    maximum_wall_normal_velocity = max(
        float(np.max(np.abs(velocity[on_left_or_right, 0]))),
        float(np.max(np.abs(velocity[on_bottom_or_top, 1]))),
    )
    if maximum_wall_normal_velocity > 1.0e-14:
        errors.append(
            "prescribed streamfunction velocity is not wall impermeable: "
            f"{maximum_wall_normal_velocity:.6g}"
        )
    backends = [
        ((solver.attrib.get("type") or ""),
         (solver.find("Linear_algebra").attrib.get("type")
          if solver.find("Linear_algebra") is not None else ""),
         (solver.findtext("Linear_algebra/Preconditioner") or ""))
        for solver in level_set.findall("LS")
    ]
    if not backends or any(
            method.strip().lower() != "gmres" or
            backend.strip().lower() != "fsils" or
            preconditioner.strip().lower() != "fsils"
            for method, backend, preconditioner in backends):
        errors.append(f"unexpected level-set linear backend contract: {backends}")
    return {
        "passed": not errors,
        "actual": actual,
        "boundaries": bcs,
        "linear_backends": backends,
        "fixed_time_steps": time_steps,
        "fixed_time_step_size": time_step_size,
        "maximum_nodal_wall_normal_velocity": maximum_wall_normal_velocity,
        "errors": errors,
    }


def run_resolution(solver: Path,
                   output_dir: Path,
                   resolution: int,
                   timeout_seconds: float,
                   bound_representability_slack: float) -> dict[str, Any]:
    case_dir = output_dir / f"wall_advection_n{resolution}"
    generation = generate_case(
        case_dir, resolution, bound_representability_slack)
    (case_dir / "generator.log").write_text(generation.stdout, encoding="utf-8")
    if generation.returncode != 0:
        return {"resolution": resolution, "passed": False,
                "errors": ["case generation failed"], "case_dir": str(case_dir)}

    contract = deck_contract(case_dir, bound_representability_slack)
    environment = os.environ.copy()
    environment.setdefault("SVV_GUI_DISABLE_VTK", "1")
    try:
        completed = subprocess.run(
            [str(solver), "solver.xml"],
            cwd=case_dir,
            env=environment,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout_seconds,
            check=False,
        )
        solver_output = completed.stdout
        returncode = completed.returncode
    except subprocess.TimeoutExpired as exc:
        solver_output = (exc.stdout or "") + (exc.stderr or "")
        returncode = 124
    (case_dir / "solver_run.log").write_text(solver_output, encoding="utf-8")

    clock, clock_errors = accepted_clock(solver_output)
    rejected_steps = len(REJECTED_RE.findall(solver_output))
    results = {
        int(match.group("step")): path
        for path in case_dir.glob("result_*.vtu")
        if (match := RESULT_RE.match(path.name))
    }
    errors = list(contract["errors"])
    errors.extend(clock_errors)
    if returncode != 0:
        errors.append(f"solver return code {returncode}")
    expected_steps = set(range(1, FIXED_TIME_STEPS + 1))
    if set(clock) != expected_steps:
        errors.append(
            f"accepted steps {sorted(clock)} do not equal {sorted(expected_steps)}"
        )
    if set(results) != expected_steps:
        errors.append(
            f"saved output steps {sorted(results)} do not equal {sorted(expected_steps)}"
        )
    if rejected_steps:
        errors.append(f"solver reported {rejected_steps} rejected step(s)")
    if clock:
        final = clock[max(clock)]
        if abs(final["time"] - FINAL_TIME) > TIME_TOLERANCE:
            errors.append(
                f"final accepted time {final['time']:.16g} != {FINAL_TIME:.16g}"
            )

    initial = pv.read(case_dir / "mesh/background/mesh-complete.mesh.vtu")
    h = LENGTH / resolution
    history = []
    previous_phi = np.asarray(
        initial.point_data["phi"], dtype=float).reshape(-1)
    bound_audit = {
        "strict_one_ring_bound_violation_dofs": 0,
        "maximum_strict_one_ring_bound_violation": 0.0,
        "representability_slack_exceeded_dofs": 0,
        "positive_patch_sign_flips": 0,
        "negative_patch_sign_flips": 0,
    }
    common_steps = sorted(set(clock) & set(results))
    exact_history = exact_phi_history(
        np.asarray(initial.points, dtype=float),
        [clock[step]["time"] for step in common_steps],
    )
    for step, expected in zip(common_steps, exact_history):
        record = clock[step]
        output = pv.read(results[step])
        candidate_phi = point_values_in_initial_order(initial, output, "phi")
        metrics = state_metrics(
            initial, output, step, record["time"],
            record["dt"], h, expected_phi=expected)
        step_bound_audit = one_ring_bound_metrics(
            initial,
            previous_phi,
            candidate_phi,
            bound_representability_slack,
            BOUND_SIGN_TOLERANCE,
        )
        metrics.update(step_bound_audit)
        bound_audit["strict_one_ring_bound_violation_dofs"] += (
            step_bound_audit["strict_one_ring_bound_violation_dofs"])
        bound_audit["maximum_strict_one_ring_bound_violation"] = max(
            bound_audit["maximum_strict_one_ring_bound_violation"],
            step_bound_audit["maximum_strict_one_ring_bound_violation"],
        )
        for name in (
                "representability_slack_exceeded_dofs",
                "positive_patch_sign_flips",
                "negative_patch_sign_flips"):
            bound_audit[name] += step_bound_audit[name]
        previous_phi = candidate_phi
        history.append(metrics)
        if metrics["representability_slack_exceeded_dofs"] != 0:
            errors.append(
                f"step {step}: "
                f"{metrics['representability_slack_exceeded_dofs']} one-ring "
                "excursion(s) exceed the numerical representability slack")
        sign_flips = (
            metrics["positive_patch_sign_flips"] +
            metrics["negative_patch_sign_flips"])
        if sign_flips != 0:
            errors.append(
                f"step {step}: {sign_flips} one-ring patch sign flip(s)")
        if metrics["impermeable_wall_exact_dry_nodes"] <= 0:
            errors.append(f"step {step}: no exact dry impermeable-wall nodes")
        if metrics["impermeable_wall_false_liquid_nodes"] != 0:
            errors.append(
                f"step {step}: {metrics['impermeable_wall_false_liquid_nodes']} "
                "exact-dry impermeable-wall nodes changed to liquid"
            )
        if metrics["phi_rms_error"] > MAX_PHI_RMS_OVER_H * h:
            errors.append(
                f"step {step}: phi RMS error {metrics['phi_rms_error']:.6g} "
                f"exceeds {MAX_PHI_RMS_OVER_H * h:.6g}"
            )
        if metrics["phi_max_abs_error"] > MAX_PHI_MAX_OVER_H * h:
            errors.append(
                f"step {step}: phi max error {metrics['phi_max_abs_error']:.6g} "
                f"exceeds {MAX_PHI_MAX_OVER_H * h:.6g}"
            )
        bottom_contact = metrics["bottom_contact_max_position_error"]
        if bottom_contact is None:
            errors.append(
                f"step {step}: expected one bottom contact point, found "
                f"{metrics['bottom_contact_count']}"
            )
        elif bottom_contact > MAX_CONTACT_ERROR_OVER_H * h:
            errors.append(
                f"step {step}: bottom contact error {bottom_contact:.6g} exceeds "
                f"{MAX_CONTACT_ERROR_OVER_H * h:.6g}"
            )
        top_contact = metrics["top_contact_max_position_error"]
        if top_contact is None:
            errors.append(
                f"step {step}: expected one top contact point, found "
                f"{metrics['top_contact_count']}"
            )
        elif top_contact > MAX_CONTACT_ERROR_OVER_H * h:
            errors.append(
                f"step {step}: top contact error {top_contact:.6g} exceeds "
                f"{MAX_CONTACT_ERROR_OVER_H * h:.6g}"
            )

    final_metrics = history[-1] if history else {}
    return {
        "resolution": resolution,
        "h": h,
        "steps": FIXED_TIME_STEPS,
        "dt": FINAL_TIME / FIXED_TIME_STEPS,
        "nominal_max_speed": float(np.max(np.linalg.norm(
            streamfunction_velocity(
                np.asarray(initial.points, dtype=float))[:, :2], axis=1))),
        "nominal_nodal_courant": (
            float(np.max(np.linalg.norm(
                streamfunction_velocity(
                    np.asarray(initial.points, dtype=float))[:, :2], axis=1))) *
            (FINAL_TIME / FIXED_TIME_STEPS) /
            min(LENGTH / resolution, TANK_HEIGHT / resolution)
        ),
        "case_dir": str(case_dir),
        "solver_returncode": returncode,
        "accepted_step_count": len(clock),
        "rejected_step_count": rejected_steps,
        "accepted_clock_complete": set(clock) == expected_steps,
        "deck_contract": contract,
        "bound_representability_slack": bound_representability_slack,
        "bound_slack_fraction_of_dry_sign_margin": (
            bound_representability_slack / (DRY_SIGN_MARGIN_OVER_H * h)),
        "bound_sign_tolerance": BOUND_SIGN_TOLERANCE,
        "bound_audit": bound_audit,
        "history": history,
        "final": final_metrics,
        "passed": not errors,
        "errors": errors,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--solver", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--resolution", type=int, action="append")
    parser.add_argument("--timeout-seconds", type=float, default=900.0)
    parser.add_argument(
        "--bound-representability-slack",
        type=float,
        default=DEFAULT_BOUND_REPRESENTABILITY_SLACK,
        help=(
            "unprojected one-ring coefficient slack used only by this "
            "qualification profile (default: %(default)g)"),
    )
    args = parser.parse_args()

    solver = args.solver.resolve()
    if not solver.is_file():
        raise FileNotFoundError(solver)
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    resolutions = args.resolution or [8, 16]
    if len(set(resolutions)) != len(resolutions) or any(n < 4 for n in resolutions):
        raise ValueError("resolutions must be distinct integers >= 4")
    validate_bound_representability_slack(
        args.bound_representability_slack, resolutions)

    runs = [run_resolution(
        solver,
        output_dir,
        n,
        args.timeout_seconds,
        args.bound_representability_slack,
    )
            for n in resolutions]
    convergence_errors: list[str] = []
    rates = []
    ordered = sorted(runs, key=lambda run: run["resolution"])
    for coarse, fine in zip(ordered[:-1], ordered[1:]):
        coarse_error = coarse.get("final", {}).get("phi_rms_error")
        fine_error = fine.get("final", {}).get("phi_rms_error")
        rate = None
        if (isinstance(coarse_error, (int, float)) and coarse_error > 0.0 and
                isinstance(fine_error, (int, float)) and fine_error > 0.0):
            rate = math.log(coarse_error / fine_error) / math.log(
                coarse["h"] / fine["h"])
        rates.append({
            "coarse_resolution": coarse["resolution"],
            "fine_resolution": fine["resolution"],
            "phi_rms_refinement_rate": rate,
        })
        fine_is_exact = (
            isinstance(fine_error, (int, float)) and
            fine_error <= REFINEMENT_EXACTNESS_FLOOR
        )
        if not fine_is_exact and (
                rate is None or rate < MIN_PHI_RMS_REFINEMENT_RATE):
            convergence_errors.append(
                f"phi RMS refinement rate {rate!r} for n="
                f"{coarse['resolution']}->{fine['resolution']} is below "
                f"{MIN_PHI_RMS_REFINEMENT_RATE}"
            )

    summary = {
        "qualification": "impermeable-wall P1 level-set advection",
        "scope": "production level-set transport isolation; not a momentum/contact-law benchmark",
        "bound_slack_interpretation": (
            "qualification-scale allowance for a deterministic non-DMP "
            "spatial-discretization excursion; not invariant-domain "
            "certification or a physical sign/accuracy tolerance"),
        "physical_parameters": {
            "length": LENGTH,
            "initial_front_x": FRONT_INITIAL_X,
            "tank_height": TANK_HEIGHT,
            "streamfunction": "A*x*(1-x/L)*y*(H-y)",
            "streamfunction_amplitude": STREAMFUNCTION_AMPLITUDE,
            "final_time": FINAL_TIME,
        },
        "fixed_gates": {
            "max_phi_rms_over_h": MAX_PHI_RMS_OVER_H,
            "max_phi_max_over_h": MAX_PHI_MAX_OVER_H,
            "max_contact_error_over_h": MAX_CONTACT_ERROR_OVER_H,
            "dry_sign_margin_over_h": DRY_SIGN_MARGIN_OVER_H,
            "minimum_phi_rms_refinement_rate": MIN_PHI_RMS_REFINEMENT_RATE,
            "refinement_exactness_floor": REFINEMENT_EXACTNESS_FLOOR,
            "maximum_false_liquid_wall_nodes": 0,
            "maximum_bound_representability_slack_over_length":
                MAX_BOUND_REPRESENTABILITY_SLACK_OVER_LENGTH,
            "configured_bound_representability_slack":
                args.bound_representability_slack,
            "bound_sign_tolerance": BOUND_SIGN_TOLERANCE,
            "maximum_representability_slack_exceeded_dofs": 0,
            "maximum_patch_sign_flips": 0,
            "maximum_rejected_steps": 0,
            "fixed_time_steps": FIXED_TIME_STEPS,
        },
        "runs": runs,
        "refinement_rates": rates,
        "convergence_errors": convergence_errors,
        "passed": all(run["passed"] for run in runs) and not convergence_errors,
    }
    (output_dir / "qualification_summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(summary, indent=2, sort_keys=True))
    return 0 if summary["passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
