# SPDX-License-Identifier: CC-BY-3.0

# Adapted from Python generated by libCellML 0.6.3 from the Physiome
# Aliev--Panfilov 1996 CellML model.
# CellML document creator: David Nickerson; cited model authors: R. R. Aliev
# and A. V. Panfilov.
# License: https://creativecommons.org/licenses/by/3.0/
# Generated from the mechanically preprocessed CellML described in README.md.
# Changes to generated Python: separate Goktepe--Kuhl alpha/b thresholds; svMP
# voltage/time/recovery-rate scaling; unused generated helper removed.
# See README.md for the exact source, revision, hashes, and generation details.

"""Physiome-derived Aliev--Panfilov model core."""

from enum import Enum
from math import *


__version__ = "0.4.0"
LIBCELLML_VERSION = "0.6.3"

STATE_COUNT = 2
VARIABLE_COUNT = 15


class VariableType(Enum):
    VARIABLE_OF_INTEGRATION = 0
    STATE = 1
    CONSTANT = 2
    COMPUTED_CONSTANT = 3
    ALGEBRAIC = 4
    EXTERNAL = 5


VOI_INFO = {"name": "t", "units": "ms", "component": "interface", "type": VariableType.VARIABLE_OF_INTEGRATION}

STATE_INFO = [
    {"name": "Vm", "units": "mV", "component": "membrane_potential", "type": VariableType.STATE},
    {"name": "v", "units": "uApmmsq", "component": "recovery_variable", "type": VariableType.STATE}
]

VARIABLE_INFO = [
    {"name": "Cm", "units": "uFpmmsq", "component": "interface", "type": VariableType.CONSTANT},
    {"name": "Vr", "units": "mV", "component": "interface", "type": VariableType.CONSTANT},
    {"name": "Vth", "units": "mV", "component": "interface", "type": VariableType.CONSTANT},
    {"name": "Vp", "units": "mV", "component": "interface", "type": VariableType.CONSTANT},
    {"name": "c1", "units": "uApmmsq", "component": "interface", "type": VariableType.CONSTANT},
    {"name": "gamma_rate", "units": "pms", "component": "interface", "type": VariableType.CONSTANT},
    {"name": "mu1_rate", "units": "pms_per_uApmmsq", "component": "interface", "type": VariableType.CONSTANT},
    {"name": "mu2", "units": "dimensionless", "component": "interface", "type": VariableType.CONSTANT},
    {"name": "Istim", "units": "uApmmsq", "component": "interface", "type": VariableType.EXTERNAL},
    {"name": "Iion", "units": "uApmmsq", "component": "ionic_current", "type": VariableType.ALGEBRAIC},
    {"name": "u", "units": "dimensionless", "component": "membrane_potential", "type": VariableType.ALGEBRAIC},
    {"name": "vstar", "units": "mV", "component": "recovery_variable", "type": VariableType.ALGEBRAIC},
    {"name": "rate", "units": "uApmmsqpmVsq", "component": "recovery_variable", "type": VariableType.COMPUTED_CONSTANT},
    {"name": "eps", "units": "pms", "component": "recovery_variable", "type": VariableType.ALGEBRAIC},
    {"name": "b", "units": "dimensionless", "component": "recovery_variable", "type": VariableType.CONSTANT}
]


def create_states_array():
    return [nan]*STATE_COUNT


def create_variables_array():
    return [nan]*VARIABLE_COUNT


def initialise_variables(voi, states, rates, variables, external_variable):
    # Cm*(Vp-Vr)=12.9 maps the generated voltage equation to the svMP time scale.
    variables[0] = 0.129
    variables[1] = -80.0
    variables[2] = -79.0
    variables[3] = 20.0
    variables[4] = 8.0
    variables[5] = 0.002/12.9
    variables[6] = 0.2/12.9
    variables[7] = 0.3
    variables[14] = 0.15
    states[0] = -80.0
    states[1] = 0.0
    variables[8] = external_variable(voi, states, rates, variables, 8)


def compute_computed_constants(variables):
    variables[12] = variables[4]/pow(variables[3]-variables[1], 2.0)


def compute_rates(voi, states, rates, variables, external_variable):
    variables[10] = (states[0]-variables[1])/(variables[3]-variables[1])
    variables[9] = variables[4]*variables[10]*(variables[10]-(variables[2]-variables[1])/(variables[3]-variables[1]))*(variables[10]-1.0)+variables[10]*states[1]
    variables[8] = external_variable(voi, states, rates, variables, 8)
    rates[0] = (variables[8]-variables[9])/variables[0]
    variables[11] = (variables[3]-variables[1])*(variables[10]-1.0-variables[14])
    variables[13] = variables[5]+variables[6]*states[1]/(variables[10]+variables[7])
    rates[1] = variables[13]*(-states[1]-variables[12]*variables[11]*(states[0]-variables[1]))
