# Use the pre-configured image from Docker Hub as the base
FROM simvascular/libraries:latest AS builder

# Get latest svMultiPhysics solver from GitHub repository
RUN git clone https://github.com/SimVascular/svMultiPhysics.git

# Trilinos build
WORKDIR /svMultiPhysics/build-trilinos
RUN cmake -DSV_USE_TRILINOS:BOOL=ON .. &&\
    make -j4

# PETSc build
WORKDIR /svMultiPhysics/build-petsc
RUN cmake -DSV_PETSC_DIR:STRING=/petsc .. &&\
    make -j4


# FINAL IMAGE with solver executable
FROM simvascular/libraries:latest AS final 

COPY --from=builder /svMultiPhysics/build-petsc /build-petsc
COPY --from=builder /svMultiPhysics/build-trilinos /build-trilinos

WORKDIR /
