#!/bin/bash

# Name of your job
#SBATCH --job-name=TEST
#SBATCH --partition=amarsden

#SBATCH --output=TEST.o%j

# Specifiy the name of the error file. The %j specifies the job ID
#SBATCH --error=TEST_ERR.e%j

# The walltime you require for your job
#SBATCH --time=24:00:00

# Job priority. Usually leave normal.
#SBATCH --qos=normal

# Number of nodes you are requesting for your job. You can have 24 processors per node
#SBATCH --nodes=1

# Amount of memory you require per node. The default is 4000 MB per node.
#SBATCH --mem=6000

# Number of processors per node
#SBATCH --ntasks-per-node=16

# Send an email to this address when the job starts and finishes
#SBATCH --mail-user=mmegally@stanford.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

# Run normal batch commands
module load system viz gcc/10.1.0 openmpi/4.1.2 vtk/9.4.1 openblas/0.3.10

srun /home/users/mmegally/darcy_build/build/svMultiPhysics-build/bin/svmultiphysics svFSI.xml

